<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1><?=$todo->getName()?></h1>
    <form action="<?=$router->pathFor('add-todo',['todoId'=>$todo->id()])?>" method="post">
        <input type="text" name="name" id="name" placeholder="New Todo" />
        <button type="Submit">Create</button>
    </form>
    <ul>
    <?php foreach ($todo->asArray() as $i=>$t): ?>
        <li>
            <form action="<?=$router->pathFor('remove-todo',['todoId'=>$todo->id()])?>" method="post">
                <label><?=$t?></label>
                <button type="submit" name="id" value="<?=$i?>">Done</button>
            </form>
        </li>
    <?php endforeach ?>
    </ul>
</body>
</html>